version: '3.8'

services:
  notesdb:  
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notes-db 
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: